version: '3.1'

services:
  smartthermostat-temperatures-backend:
    build: .
    image: "smartthermostat-temperatures-backend:latest"
    container_name: "smartthermostat-temperatures-backend"
    restart: unless-stopped
    environment:
      TEMPERATURES_SERVER_PORT: "${TEMPERATURES_SERVER_PORT}"
    ports:
      - "${TEMPERATURES_SERVER_PORT}:${TEMPERATURES_SERVER_PORT}"
    depends_on:
      - smartthermostat-temperatures-db
      - smartthermostat-rabbitmq
    networks:
      - app

  smartthermostat-temperatures-db:
    image: "mysql:8"
    container_name: "smartthermostat-temperatures-db"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${TEMPERATURES_DATABASE_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - smartthermostat-temperatures-db:/var/lib/mysql
    networks:
      - app

  smartthermostat-rabbitmq:
    container_name: "smartthermostat-rabbitmq"
    image: "rabbitmq:3.9.13-management"
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "9000:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - app

volumes:
  smartthermostat-temperatures-db:
    driver: local

networks:
  app: