version: '3.1'

services:
  smartthermostat-backoffice-db:
    image: "mysql:8"
    container_name: "smartthermostat-backoffice-db"
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${BACKOFFICE_DATABASE_NAME}"
      MYSQL_USER: "${BACKOFFICE_DATABASE_USER}"
      MYSQL_PASSWORD: "${BACKOFFICE_DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${BACKOFFICE_DATABASE_PASSWORD}"
    ports:
      - "${BACKOFFICE_DATABASE_PORT}:${BACKOFFICE_DATABASE_PORT}"
    volumes:
      - smartthermostat-backoffice-db:/var/lib/mysql
    networks:
      - app

  smartthermostat-rabbitmq:
    image: "rabbitmq:3.9.13-management"
    container_name: "smartthermostat-rabbitmq"
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "9000:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_LOGIN}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    networks:
      - app

volumes:
  smartthermostat-backoffice-db:
    driver: local

networks:
  app:
