version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${TEMPERATURES_DATABASE_NAME}"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - "10000:8080"
    networks:
      - db
      - default

volumes:
  db:
    driver: local

networks:
  db: