version: '3.1'

services:
  smartthermostat-backend:
    build: .
    image: smartthermostat-backend
    container_name: smartthermostat-backend
    environment:
      TEMPERATURES_SERVER_PORT: ${TEMPERATURES_SERVER_PORT}
    ports:
      - "${TEMPERATURES_SERVER_PORT}:${TEMPERATURES_SERVER_PORT}"
    depends_on:
      - db
    links:
      - db
    networks:
      - db
      - default

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    networks:
      - db
      - default

volumes:
  db:
    driver: local

networks:
  db: